# Generated by Django 5.1.5 on 2025-01-28 16:12

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('objective', models.TextField()),
                ('address', models.TextField()),
                ('total_experience', models.FloatField(help_text='Total experience in years')),
                ('slug', models.SlugField(unique=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.role')),
                ('skills', models.ManyToManyField(related_name='developers_skills', to='admin_portal.skill')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Native or Bilingual Proficiency', 'Native or Bilingual'), ('Full Professional Proficiency', 'Full Professional'), ('Professional Working Proficiency', 'Professional Working'), ('Limited Working Proficiency', 'Limited Working'), ('Elementary Proficiency', 'Elementary'), ('Beginner', 'Beginner')], max_length=255)),
                ('language_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.language')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='dev_resume.developerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_description', tinymce.models.HTMLField(default='\n        <ul>\n            <li>JD 1</li>\n            <li>JD 2</li>\n            <li>JD 3</li>\n        </ul>\n        ')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.role')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='dev_resume.developerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('university', models.CharField(max_length=255)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.degree')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='dev_resume.developerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(default='\n        <ul>\n            <li>Description 1</li>\n            <li>Description 2</li>\n            <li>Description 3</li>\n        </ul>\n        ')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dev_resume.developerprofile')),
                ('developer_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_portal.role')),
                ('key_skills', models.ManyToManyField(related_name='projects', to='admin_portal.skill')),
            ],
        ),
    ]
