# Generated by Django 5.1.5 on 2025-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
