# Generated by Django 5.1.5 on 2025-01-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_resume', '0002_alter_developerprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
